const D=window.CAMPAIGN,$=s=>document.querySelector(s),by=(a,id)=>a.find(x=>x.id===id);
let state={route:"home",id:null,filter:"All"};
const app=$("#app"),nav=$("#nav");
function route(r,id){state={...state,route:r,id:id||null};location.hash=id?r+"/"+id:r;render();nav.classList.remove("open");scrollTo(0,0)}
function card(x,kind){return `<button class="card" data-open="${kind}" data-id="${x.id}"><div class="meta">${x.type||x.kind||""}${x.clan?" · "+x.clan:""}</div><h3>${x.name||x.title}</h3><p>${x.summary||""}</p></button>`}
function related(ids,type){if(!ids?.length)return"";let a=type==="people"?D.people:D.places;return `<div class="related"><div class="eyebrow">RELATED ${type.toUpperCase()}</div><div class="grid two" style="margin-top:10px">${ids.map(id=>card(by(a,id),type)).join("")}</div></div>`}
function home(){return `<section class="hero"><div class="eyebrow">VAMPIRE: THE MASQUERADE // LAKE SUPERIOR</div><h1>DULUTH<br>BY NIGHT</h1><p>The lake is black. The harbor never sleeps. Every favor leaves a mark.</p></section>
<section class="status"><div><small>CURRENT NIGHT</small>After Sept. 11</div><div><small>COTERIE STATUS</small>Playing Both Sides</div><div><small>CURRENT LEAD</small>Kyra's Haven</div><div><small>NEXT STOP</small>Chantry Library</div></section>
<h2 class="section-title">Tonight in Duluth</h2><section class="card" style="cursor:default;border-left-color:#8e1e25"><div class="eyebrow">WHERE WE LEFT OFF // SEPTEMBER 11</div><h2>Blacklight</h2><p>The coterie met Portia to investigate the sigils and drowned creatures beneath Nopeming. She connected their discoveries to whispers of the Bahari and invited Iris alone to continue the research at the Tremere Chantry.</p><p style="margin-top:10px">Meanwhile, Spokes and his bicycle gang are hunting for Kyra's haven and mapping her security.</p><div class="badges"><span class="badge">IRIS → CHANTRY</span><span class="badge">SPOKES → HUNT KYRA</span><span class="badge">MAXWELL / JACKSON</span><span class="badge">TARGET → BLISS</span></div></section>
<h2 class="section-title">Active Threads</h2><div class="grid two">${D.threads.map(x=>card(x,"threads")).join("")}</div>
<h2 class="section-title">Latest Chronicle</h2>${card(D.sessions[0],"chronicle")}
<h2 class="section-title">Faces to Remember</h2><div class="grid three">${["spokes","portia","kyra"].map(id=>card(by(D.people,id),"people")).join("")}</div>`}
function people(){let types=["All",...new Set(D.people.map(x=>x.type))],pool=state.filter==="All"?D.people:D.people.filter(x=>x.type===state.filter);return `<h1>Kindred & Others</h1><div class="eyebrow">WHO ARE YOU LOOKING FOR?</div><div class="filters">${types.map(t=>`<button class="chip ${state.filter===t?"active":""}" data-filter="${t}">${t}</button>`).join("")}</div><div class="grid three">${pool.map(x=>card(x,"people")).join("")}</div>`}
function places(){let roots=D.places.filter(x=>!x.parent);return `<h1>Places</h1><p class="meta">GEOGRAPHY FIRST — OPEN A CITY OR COMMUNITY TO DRILL DOWN</p><div class="grid two">${roots.map(x=>card(x,"places")).join("")}</div>`}
function threads(){return `<h1>Active Threads</h1><div class="grid two">${D.threads.map(x=>card(x,"threads")).join("")}</div>`}
function chronicle(){return `<h1>Chronicle</h1><div class="grid two">${D.sessions.map(x=>card(x,"chronicle")).join("")}</div>`}
function detail(type,id){let a=type==="people"?D.people:type==="places"?D.places:type==="threads"?D.threads:D.sessions,x=by(a,id);if(!x)return'<div class="empty">Record not found.</div>';let parent=x.parent?by(D.places,x.parent):null;let kids=x.children?.map(id=>by(D.places,id));return `<div class="detail"><button class="back" data-route="${type}">← BACK TO ${type.toUpperCase()}</button><div class="crumbs" style="margin-top:24px">${parent?parent.name+" / ":""}${x.type||x.kind||x.date||""}</div><h1>${x.name||x.title}</h1><p>${x.summary||""}</p>${kids?.length?`<div class="related"><div class="eyebrow">INSIDE ${x.name.toUpperCase()}</div><div class="grid two" style="margin-top:10px">${kids.map(y=>card(y,"places")).join("")}</div></div>`:""}${type==="threads"?related(x.people,"people")+related(x.places,"places"):""}${type==="places"?related(D.people.filter(p=>p.place===x.id).map(p=>p.id),"people"):""}</div>`}
function render(){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===state.route));app.innerHTML=state.id?detail(state.route,state.id):state.route==="home"?home():state.route==="people"?people():state.route==="places"?places():state.route==="threads"?threads():chronicle()}
document.addEventListener("click",e=>{let r=e.target.closest("[data-route]");if(r){route(r.dataset.route);return}let o=e.target.closest("[data-open]");if(o){route(o.dataset.open,o.dataset.id);return}let f=e.target.closest("[data-filter]");if(f){state.filter=f.dataset.filter;render()}})
$("#menuBtn").onclick=()=>nav.classList.toggle("open");
function boot(){let [r,id]=location.hash.replace("#","").split("/");if(["home","people","places","threads","chronicle"].includes(r)){state.route=r;state.id=id||null}render()}window.addEventListener("hashchange",boot);boot();