// Coterie is a reusable organization record; permission checks remain in Supabase.
(function(root){
 const ID='organization:player-coterie',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let data,model;
 const st=()=>root.campaignSession?.isStoryteller;
 const ref=id=>{const r=model.byId(id);return r?`<a href="#${model.routeFor(r)}/${encodeURIComponent(r.id)}">${esc(r.name)}</a>`:'Unknown';};
 function picker(kind,current){
  const allowed=kind==='member'?['person']:kind==='haven'?['place']:kind==='boon'?['person','organization']:null;
  const records=data.records.filter(r=>(!allowed||allowed.includes(r.recordType))&&!r.archivedAt&&(['players','public'].includes(r.audience)||r.id===current)).sort((a,b)=>a.displayName.localeCompare(b.displayName));
  return `<label>${kind==='member'?'Character':kind==='haven'?'Haven':kind==='boon'?'Counterparty':'Related record (optional)'}<select name="reference_record_id"><option value="">${kind==='member'?'Choose a character':'Unknown / none'}</option>${records.map(r=>`<option value="${esc(r.id)}" ${r.id===current?'selected':''}>${esc(r.displayName)}${['players','public'].includes(r.audience)?'':' (not revealed)'}</option>`).join('')}</select></label>`;
 }
 function entryForm(kind,entry){
  const value=entry?.value||{},current=kind==='member'?entry?.fromRecordId:entry?.referenceRecordId;
  return `<form data-coterie-kind="${kind}" data-entry-id="${esc(entry?.id||'')}" data-revision="${entry?.revision||0}">${!['member','haven'].includes(kind)?`<label>Name<input name="title" required value="${esc(entry?.title)}"></label>`:''}${picker(kind,current)}${kind==='boon'?`<label>Direction<select name="direction"><option value="owed_by_coterie" ${value.direction==='owed_by_coterie'?'selected':''}>Coterie owes</option><option value="owed_to_coterie" ${value.direction==='owed_to_coterie'?'selected':''}>Owed to the coterie</option></select></label><label>Boon type<input name="boon_type" value="${esc(value.boonType)}" placeholder="Unknown, minor, major…"></label><label>Status<select name="status"><option value="outstanding" ${value.status==='outstanding'?'selected':''}>Outstanding</option><option value="settled" ${value.status==='settled'?'selected':''}>Settled</option></select></label>`:''}${kind==='resource'?`<label>Quantity / rating<input name="quantity" value="${esc(value.quantity)}" placeholder="Leave unknown if unrecorded"></label>`:''}${kind!=='member'?`<label>Details<textarea name="body" rows="4">${esc(entry?.body)}</textarea></label>`:''}<button class="chip" type="submit">${entry?'Save changes':'Add '+kind}</button><p role="status" aria-live="polite"></p></form>`;
 }
 function add(kind){return st()?`<details class="coterie-editor"><summary>Add ${kind}</summary>${entryForm(kind)}</details>`:'';}
 function edit(kind,entry){return st()?`<details class="coterie-editor"><summary>Edit ${kind}</summary>${entryForm(kind,entry)}</details>`:'';}
 function entries(kind,items){return items.filter(x=>x.fieldKey==='coterie.'+kind&&!x.archivedAt);}
 function render(campaign,campaignModel){
  data=campaign;model=campaignModel;
  const r=model.byId(ID);
  if(!r)return `<h1>Coterie</h1><p>No coterie workspace is available yet.</p>${st()?'<button class="chip" data-setup-coterie type="button">Set up coterie</button><p id="coterieMessage" role="status" aria-live="polite"></p>':''}`;
  const items=model.itemsFor(ID),members=data.relationships.filter(x=>x.relationshipType==='member_of'&&x.toRecordId===ID&&!x.archivedAt),haven=items.find(x=>x.fieldKey==='coterie.haven'&&!x.archivedAt),notes=items.find(x=>x.fieldKey==='notes.player'&&!x.archivedAt),boons=entries('boon',items),resources=entries('resource',items);
  const ledger=direction=>boons.filter(x=>x.value?.direction===direction).map(x=>`<article class="coterie-entry"><h3>${esc(x.title)}</h3><p>${ref(x.referenceRecordId)} · ${esc(x.value?.boonType||'Type unknown')} · ${esc(x.value?.status||'Status unknown')}</p>${x.body?`<p class="rules-text">${esc(x.body)}</p>`:''}${edit('boon',x)}</article>`).join('')||'<p class="empty">No boons recorded.</p>';
  return `<article class="coterie-page"><h1>${esc(r.name)}</h1>${st()?root.CampaignEditor.recordLink(ID):''}<p id="coterieMessage" role="status" aria-live="polite"></p><button class="chip" type="button" data-coterie-reload>Reload saved coterie</button><div class="coterie-grid"><section class="npc-panel"><h2>Player characters</h2>${members.length?`<ul class="record-links">${members.map(x=>`<li>${ref(x.fromRecordId)}${edit('member',x)}</li>`).join('')}</ul>`:'<p class="empty">No characters linked yet.</p>'}${add('member')}${st()?'<p class="mechanic-notes">Reveal a character’s name in Storyteller tools before adding them. Membership does not grant character-sheet editing.</p>':''}</section><section class="npc-panel"><h2>Haven</h2><p>${haven?.referenceRecordId?ref(haven.referenceRecordId):'Unknown'}</p>${haven?.body?`<p class="rules-text">${esc(haven.body)}</p>`:''}${haven?edit('haven',haven):''}${st()&&haven?.audience==='storyteller'?'<p class="mechanic-notes">This haven link is Storyteller-only. Reveal it through the record editor when ready.</p>':''}</section></div><section class="npc-panel"><h2>Boons</h2><div class="coterie-grid"><div><h3>Coterie owes</h3>${ledger('owed_by_coterie')}</div><div><h3>Owed to the coterie</h3>${ledger('owed_to_coterie')}</div></div>${add('boon')}</section><section class="npc-panel"><h2>Resources</h2>${resources.length?`<div class="coterie-grid">${resources.map(x=>`<article class="coterie-entry"><h3>${esc(x.title)}</h3>${x.value?.quantity?`<p>Quantity / rating: ${esc(x.value.quantity)}</p>`:''}${x.referenceRecordId?`<p>${ref(x.referenceRecordId)}</p>`:''}${x.body?`<p class="rules-text">${esc(x.body)}</p>`:''}${edit('resource',x)}</article>`).join('')}</div>`:'<p class="empty">No resources recorded.</p>'}${add('resource')}</section><section class="npc-panel coterie-notes"><h2>Player notes</h2>${notes&&root.campaignSession?`<form data-note-id="${esc(notes.id)}"><label>Shared campaign notes<textarea name="body" rows="16">${esc(notes.body)}</textarea></label><button type="submit" class="chip">Save notes</button><p role="status" aria-live="polite"></p></form>`:'<p class="empty">No shared notes available.</p>'}</section></article>`;
 }
 document.addEventListener('submit',async event=>{
  const form=event.target.closest('form[data-coterie-kind]');if(!form)return;event.preventDefault();const button=form.querySelector('button'),message=form.querySelector('[role=status]');if(button.disabled)return;button.disabled=true;message.textContent='Saving…';let committed=false;
  try{await root.campaignSession.saveCoterie(form.dataset.coterieKind,form.dataset.entryId,Number(form.dataset.revision),Object.fromEntries(new FormData(form)));committed=true;await root.refreshCampaignViews();const next=document.querySelector('#coterieMessage');if(next)next.textContent='Coterie updated.';}
  catch(error){message.textContent=(committed?'Saved, but reload failed. Reload saved coterie before editing again. ':'')+error.message;}finally{button.disabled=false;}
 });
 document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-setup-coterie],[data-coterie-reload]');if(!button)return;if(button.disabled)return;button.disabled=true;const message=document.querySelector('#coterieMessage');message.textContent='Loading…';
  try{if(button.hasAttribute('data-setup-coterie'))await root.campaignSession.saveCoterie('setup',null,0,{});await root.refreshCampaignViews();}catch(error){message.textContent=error.message;button.disabled=false;}
 });
 root.Coterie={render};
})(globalThis);
